// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanJunk(arg1) {
  return window['go']['app']['App']['CleanJunk'](arg1);
}

export function GetCleanHistory() {
  return window['go']['app']['App']['GetCleanHistory']();
}

export function GetDiskList() {
  return window['go']['app']['App']['GetDiskList']();
}

export function GetGPUInfo() {
  return window['go']['app']['App']['GetGPUInfo']();
}

export function GetMemOptStats() {
  return window['go']['app']['App']['GetMemOptStats']();
}

export function GetNetTraffic() {
  return window['go']['app']['App']['GetNetTraffic']();
}

export function GetNetTrafficStats() {
  return window['go']['app']['App']['GetNetTrafficStats']();
}

export function GetProcessList() {
  return window['go']['app']['App']['GetProcessList']();
}

export function GetRealtimeStats() {
  return window['go']['app']['App']['GetRealtimeStats']();
}

export function GetSystemInfo() {
  return window['go']['app']['App']['GetSystemInfo']();
}

export function KillProcess(arg1) {
  return window['go']['app']['App']['KillProcess'](arg1);
}

export function OptimizeMemory() {
  return window['go']['app']['App']['OptimizeMemory']();
}

export function ScanJunk() {
  return window['go']['app']['App']['ScanJunk']();
}

export function ScanLargeFiles(arg1, arg2) {
  return window['go']['app']['App']['ScanLargeFiles'](arg1, arg2);
}
