// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CheckUpdate():Promise<model.UpdateInfo>;

export function CleanJunk(arg1:Array<string>):Promise<model.CleanResult>;

export function GetAppVersion():Promise<string>;

export function GetCleanHistory():Promise<model.CleanHistoryStats>;

export function GetDiskList():Promise<Array<model.DiskInfo>>;

export function GetGPUInfo():Promise<model.GPUResult>;

export function GetMemOptStats():Promise<model.MemOptStats>;

export function GetNetTraffic():Promise<model.NetTrafficResult>;

export function GetNetTrafficStats():Promise<model.NetTrafficStats>;

export function GetProcessList():Promise<Array<model.ProcessInfo>>;

export function GetRealtimeStats():Promise<model.RealtimeStats>;

export function GetSystemInfo():Promise<model.SystemInfo>;

export function KillProcess(arg1:number):Promise<void>;

export function OptimizeMemory():Promise<model.MemoryOptResult>;

export function ScanJunk():Promise<Array<model.ScanResult>>;

export function ScanLargeFiles(arg1:string,arg2:number):Promise<model.DiskScanResult>;
